# build and flash the gallery devices
#
# "make" or "make all" will compile the wsd_gallery.ino file into wsd_gallery_Gnn.bin
# if no bin file exists or the bin file is out of date.
#
# "make clean" removes all the bin files and will force a recompile the next time a
# make is run.
# 
# "make flash" will flash all the gallery devices with the current bin file.  If no 
# bin file exists, or the bin file is out of date, the bin file is re-built.
#
# "make flashgNN" where NN is a number between 00 and 29 will flash the current
# bin file to the specified device only.  If no bin file exists, or the bin file
# is out of date, the bin file is re-built.

INCLUDES = ../include/wsd_defines.h

#all: wsd_gallery_TG00.bin 

all: wsd_gallery_G00.bin \
     wsd_gallery_G01.bin \
     wsd_gallery_G02.bin \
     wsd_gallery_G03.bin \
     wsd_gallery_G04.bin \
     wsd_gallery_G05.bin \
     wsd_gallery_G06.bin \
     wsd_gallery_G07.bin \
     wsd_gallery_G08.bin \
     wsd_gallery_G09.bin \
     wsd_gallery_G10.bin \
     wsd_gallery_G11.bin \
     wsd_gallery_G12.bin \
     wsd_gallery_G13.bin \
     wsd_gallery_G14.bin \
     wsd_gallery_G15.bin \
     wsd_gallery_G16.bin \
     wsd_gallery_G17.bin \
     wsd_gallery_G18.bin \
     wsd_gallery_G19.bin \
     wsd_gallery_G20.bin \
     wsd_gallery_G21.bin \
     wsd_gallery_G22.bin \
     wsd_gallery_G23.bin \
     wsd_gallery_G24.bin \
     wsd_gallery_G25.bin \
     wsd_gallery_G26.bin \
     wsd_gallery_G27.bin \
     wsd_gallery_G28.bin \
     wsd_gallery_G29.bin 

clean:
	rm -fr wsd_gallery_*.bin 

#wsd_gallery_TG00.bin: wsd_gallery.ino wsd_sensor_TS00.h $(INCLUDES)
#	cp wsd_sensor_TS00.h wsd_sensor.h
#	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G00.bin: wsd_gallery.ino wsd_sensor_S00.h $(INCLUDES)
	cp wsd_sensor_S00.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G01.bin: wsd_gallery.ino wsd_sensor_S01.h $(INCLUDES)
	cp wsd_sensor_S01.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G02.bin: wsd_gallery.ino wsd_sensor_S02.h $(INCLUDES)
	cp wsd_sensor_S02.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G03.bin: wsd_gallery.ino wsd_sensor_S03.h $(INCLUDES)
	cp wsd_sensor_S03.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G04.bin: wsd_gallery.ino wsd_sensor_S04.h $(INCLUDES)
	cp wsd_sensor_S04.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G05.bin: wsd_gallery.ino wsd_sensor_S05.h $(INCLUDES)
	cp wsd_sensor_S05.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G06.bin: wsd_gallery.ino wsd_sensor_S06.h $(INCLUDES)
	cp wsd_sensor_S06.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G07.bin: wsd_gallery.ino wsd_sensor_S07.h $(INCLUDES)
	cp wsd_sensor_S07.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G08.bin: wsd_gallery.ino wsd_sensor_S08.h $(INCLUDES)
	cp wsd_sensor_S08.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G09.bin: wsd_gallery.ino wsd_sensor_S09.h $(INCLUDES)
	cp wsd_sensor_S09.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G10.bin: wsd_gallery.ino wsd_sensor_S10.h $(INCLUDES)
	cp wsd_sensor_S10.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G11.bin: wsd_gallery.ino wsd_sensor_S11.h $(INCLUDES)
	cp wsd_sensor_S11.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G12.bin: wsd_gallery.ino wsd_sensor_S12.h $(INCLUDES)
	cp wsd_sensor_S12.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G13.bin: wsd_gallery.ino wsd_sensor_S13.h $(INCLUDES)
	cp wsd_sensor_S13.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G14.bin: wsd_gallery.ino wsd_sensor_S14.h $(INCLUDES)
	cp wsd_sensor_S14.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G15.bin: wsd_gallery.ino wsd_sensor_S15.h $(INCLUDES)
	cp wsd_sensor_S15.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G16.bin: wsd_gallery.ino wsd_sensor_S16.h $(INCLUDES)
	cp wsd_sensor_S16.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G17.bin: wsd_gallery.ino wsd_sensor_S17.h $(INCLUDES)
	cp wsd_sensor_S17.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G18.bin: wsd_gallery.ino wsd_sensor_S18.h $(INCLUDES)
	cp wsd_sensor_S18.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G19.bin: wsd_gallery.ino wsd_sensor_S19.h $(INCLUDES)
	cp wsd_sensor_S19.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G20.bin: wsd_gallery.ino wsd_sensor_S20.h $(INCLUDES)
	cp wsd_sensor_S20.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G21.bin: wsd_gallery.ino wsd_sensor_S21.h $(INCLUDES)
	cp wsd_sensor_S21.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G22.bin: wsd_gallery.ino wsd_sensor_S22.h $(INCLUDES)
	cp wsd_sensor_S22.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G23.bin: wsd_gallery.ino wsd_sensor_S23.h $(INCLUDES)
	cp wsd_sensor_S23.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G24.bin: wsd_gallery.ino wsd_sensor_S24.h $(INCLUDES)
	cp wsd_sensor_S24.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G25.bin: wsd_gallery.ino wsd_sensor_S25.h $(INCLUDES)
	cp wsd_sensor_S25.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G26.bin: wsd_gallery.ino wsd_sensor_S26.h $(INCLUDES)
	cp wsd_sensor_S26.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G27.bin: wsd_gallery.ino wsd_sensor_S27.h $(INCLUDES)
	cp wsd_sensor_S27.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G28.bin: wsd_gallery.ino wsd_sensor_S28.h $(INCLUDES)
	cp wsd_sensor_S28.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@
 
wsd_gallery_G29.bin: wsd_gallery.ino wsd_sensor_S29.h $(INCLUDES)
	cp wsd_sensor_S29.h wsd_sensor.h
	particle compile p $< wsd_sensor.h $(INCLUDES) --saveto $@

#flash: flashtg00 

flash: flashg00 \
       flashg01 \
       flashg02 \
       flashg03 \
       flashg04 \
       flashg05 \
       flashg06 \
       flashg07 \
       flashg08 \
       flashg09 \
       flashg10 \
       flashg11 \
       flashg12 \
       flashg13 \
       flashg14 \
       flashg15 \
       flashg16 \
       flashg17 \
       flashg18 \
       flashg19 \
       flashg20 \
       flashg21 \
       flashg22 \
       flashg23 \
       flashg24 \
       flashg25 \
       flashg26 \
       flashg27 \
       flashg28 \
       flashg29 

#flashtg00: wsd_gallery_TG00.bin
#	particle flash TG00 wsd_gallery_TG00.bin

flashg00: wsd_gallery_G00.bin
	particle flash G00 wsd_gallery_G00.bin

flashg01: wsd_gallery_G01.bin 
	particle flash G01 wsd_gallery_G01.bin

flashg02: wsd_gallery_G02.bin 
	particle flash G02 wsd_gallery_G02.bin

flashg03: wsd_gallery_G03.bin 
	particle flash G03 wsd_gallery_G03.bin

flashg04: wsd_gallery_G04.bin 
	particle flash G04 wsd_gallery_G04.bin

flashg05: wsd_gallery_G05.bin 
	particle flash G05 wsd_gallery_G05.bin

flashg06: wsd_gallery_G06.bin 
	particle flash G06 wsd_gallery_G06.bin

flashg07: wsd_gallery_G07.bin 
	particle flash G07 wsd_gallery_G07.bin

flashg08: wsd_gallery_G08.bin 
	particle flash G08 wsd_gallery_G08.bin

flashg09: wsd_gallery_G09.bin 
	particle flash G09 wsd_gallery_G09.bin

flashg10: wsd_gallery_G10.bin 
	particle flash G10 wsd_gallery_G10.bin

flashg11: wsd_gallery_G11.bin 
	particle flash G11 wsd_gallery_G11.bin

flashg12: wsd_gallery_G12.bin 
	particle flash G12 wsd_gallery_G12.bin

flashg13: wsd_gallery_G13.bin 
	particle flash G13 wsd_gallery_G13.bin

flashg14: wsd_gallery_G14.bin 
	particle flash G14 wsd_gallery_G14.bin

flashg15: wsd_gallery_G15.bin 
	particle flash G15 wsd_gallery_G15.bin

flashg16: wsd_gallery_G16.bin 
	particle flash G16 wsd_gallery_G16.bin

flashg17: wsd_gallery_G17.bin 
	particle flash G17 wsd_gallery_G17.bin

flashg18: wsd_gallery_G18.bin 
	particle flash G18 wsd_gallery_G18.bin

flashg19: wsd_gallery_G19.bin 
	particle flash G19 wsd_gallery_G19.bin

flashg20: wsd_gallery_G20.bin 
	particle flash G20 wsd_gallery_G20.bin

flashg21: wsd_gallery_G21.bin 
	particle flash G21 wsd_gallery_G21.bin

flashg22: wsd_gallery_G22.bin 
	particle flash G22 wsd_gallery_G22.bin

flashg23: wsd_gallery_G23.bin 
	particle flash G23 wsd_gallery_G23.bin

flashg24: wsd_gallery_G24.bin 
	particle flash G24 wsd_gallery_G24.bin

flashg25: wsd_gallery_G25.bin 
	particle flash G25 wsd_gallery_G25.bin

flashg26: wsd_gallery_G26.bin 
	particle flash G26 wsd_gallery_G26.bin

flashg27: wsd_gallery_G27.bin 
	particle flash G27 wsd_gallery_G27.bin

flashg28: wsd_gallery_G28.bin 
	particle flash G28 wsd_gallery_G28.bin

flashg29: wsd_gallery_G29.bin 
	particle flash G29 wsd_gallery_G29.bin

